#packages needed
require(dplyr)
require(tidyquant)

simultaneous <- function(csv_file = "./gen/data-preparation/input/releases.csv"){
  
  #' Creates dummy variable whether the show has been dropped all
  #' at once, or whether a season had multiple release dates. This
  #' dummy is stored in simultaneous.
  #' 
  #' @param csv_file Output generated by API of TMDb, consisting
  #' of all the release dates of TV shows and movies
  
  # import release dates csv
  releases <- read.csv(csv_file, sep = ";")
  
  # set release data as dates
  releases$release_data <- as.Date(releases$release_date, "%Y-%m-%d"))
  
  # create dummy whether whole season is dropped simultaneously
  releases <- releases %>%
    group_by(tmdb_id, season_number) %>%
    mutate(simultaneous = ifelse(n_distinct(release_date) == 1, 1,0))
  
  return(releases)
}

simultaneous_df <- simultaneous()

# create directory
dir.create("./gen/data-preparation/temp")

# save transformed data
save(simultaneous_df, file= "./gen/data-preparation/temp/transform_releases.RData")
